project:
  type: website
  render:
    - "*.qmd"
    - "!*.ipynb"

website:
  title: "Café Alpha"
  bread-crumbs: false
  navbar:
    background: "#769FCD"
    foreground: '#F7FBFC'
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:   
    #title: "Integrity"
    style: docked
    search: false
    background: "#D6E6F2"
    logo: img/alpha.png
    collapse-level: 3
    contents: 
      - section: "**Music**"
        contents: 
        - music/songs.qmd
        - music/albums.qmd
      - section: "**Books**"
        contents: 
        - text: "Fiction"
          href: books/books_fiction.qmd
        - text: "Manga"
          href: books/books_manga.qmd
        - text: "Non-Fiction"
          href: books/books_nonfiction.qmd
      - section: "**Films**"
        contents: 
        - films/films.qmd
      - section: "**Video Games**"
        contents: 
        - games/games.qmd

format:
  html:
    theme:
      - zephyr
      - brand
    css: styles.css
    toc: true
    include-after-body: scripts.js

execute:
  freeze: auto



