---
title: "Top 100 Songs"
format: html
toc: false
echo: false
---


The greatest songs of all time!!! (According to me)\


::: {.callout-note title="Note"}
- One song per artist.
- Classical music is not eligible and will be covered in a separate list.
:::


<div class="dropdown">
  <button class="btn btn-primary dropdown-toggle" type="button"
          data-bs-toggle="dropdown" aria-expanded="false">
    Sort
  </button>
  <ul class="dropdown-menu">
    <li>
      <a class="dropdown-item" href="#"
         onclick="sortSections('rank','desc'); return false;">
        Rank
      </a>
    </li>
    <li>
      <a class="dropdown-item" href="#"
         onclick="sortSections('year','desc'); return false;">
        Year
      </a>
    </li>
    <li>
      <a class="dropdown-item" href="#"
         onclick="sortSections('sad','desc'); return false;">
        Sad
      </a>
    </li>
    <li>
      <a class="dropdown-item" href="#"
         onclick="sortSections('angry','desc'); return false;">
        Angry
      </a>
    </li>
    <li>
      <a class="dropdown-item" href="#"
         onclick="sortSections('happy','desc'); return false;">
        Happy
      </a>
    </li>
    <li>
      <a class="dropdown-item" href="#"
         onclick="sortSections('dark','desc'); return false;">
        Dark
      </a>
    </li>
    <li>
      <a class="dropdown-item" href="#"
         onclick="sortSections('groovy','desc'); return false;">
        Groovy
      </a>
    </li>
    <li>
      <a class="dropdown-item" href="#"
         onclick="sortSections('dreamy','desc'); return false;">
        Dreamy
      </a>
    </li>
    <li>
      <a class="dropdown-item" href="#"
         onclick="sortSections('passion','desc'); return false;">
        Passion
      </a>
    </li>
  </ul>
</div>

<!---
<div class="d-flex gap-4 mb-3">
<div class="form-check form-switch">
<input class="form-check-input" type="checkbox" id="toggleMaxMood">
<label class="form-check-label" for="toggleMaxMood">Max. Mood</label>
</div>

<div class="form-check form-switch mt-4">
<input class="form-check-input" type="checkbox" id="toggleMood" checked>
<label class="form-check-label" for="toggleMood">Mood Levels</label>
</div>

<div class="form-check form-switch mt-4">
<input class="form-check-input" type="checkbox" id="toggleTags" checked>
<label class="form-check-label" for="toggleTags">Tags</label>
</div></div>
--->


<div class="songs">## 100. Eric B. & Rakim - Juice (Know the Ledge){.song data-passion="0" data-dreamy="0" data-dark="0" data-groovy="1" data-angry="1" data-happy="0" data-sad="0" data-rank="100" data-hasmaxattribute="False" data-year="1992"}
**Album:** *Juice (Know the Ledge) * (1992)\
**Genres:** Boom Bap
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Angry</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #FF5D45FF; width:20.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Groovy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #9C6B4EFF; width:20.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="OPkWYTUiPTo"></lite-youtube></div></details>
## 99. Metallica - For Whom the Bell Tolls{.song data-passion="0" data-dreamy="0" data-dark="3" data-groovy="2" data-angry="2" data-happy="0" data-sad="0" data-rank="99" data-hasmaxattribute="False" data-year="1984"}
**Album:** *Ride the Lightning* (1984)\
**Genres:** Thrash Metal
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Angry</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #FF5D45FF; width:40.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dark</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #1B1B1BFF; width:60.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Groovy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #9C6B4EFF; width:40.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="B_HSa1dEL9s"></lite-youtube></div></details>
## 98. The Beatles - Here Comes the Sun{.song data-passion="0" data-dreamy="1" data-dark="0" data-groovy="0" data-angry="0" data-happy="5" data-sad="0" data-rank="98" data-hasmaxattribute="True" data-year="1969"}
**Album:** *Abbey Road* (1969)\
**Genres:** Sunshine Pop
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Happy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #6CC5B0FF; width:100.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dreamy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #F0BD3CFF; width:20.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="tDEzmaZHuS0"></lite-youtube></div></details>
## 97. Curtis Mayfield - Move On Up{.song data-passion="0" data-dreamy="0" data-dark="0" data-groovy="4" data-angry="0" data-happy="4" data-sad="0" data-rank="97" data-hasmaxattribute="False" data-year="1970"}
**Album:** *Curtis* (1970)\
**Genres:** Funk
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Happy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #6CC5B0FF; width:80.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Groovy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #9C6B4EFF; width:80.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="6Z66wVo7uNw"></lite-youtube></div></details>
## 96. Dälek - Police State Is Nervous{.song data-passion="0" data-dreamy="0" data-dark="1" data-groovy="0" data-angry="3" data-happy="0" data-sad="2" data-rank="96" data-hasmaxattribute="False" data-year="2014"}
**Album:** *nan* (2014)\
**Genres:** Political Hip Hop
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"><span class="badge bg-primary rounded-pill">Anti-fascist Anthem</span></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Sad</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #4269D0FF; width:40.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Angry</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #FF5D45FF; width:60.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dark</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #1B1B1BFF; width:20.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="gBByC9BebX4"></lite-youtube></div></details>
## 95. Ton Steine Scherben - Macht kaputt was euch kaputt macht{.song data-passion="2" data-dreamy="0" data-dark="0" data-groovy="1" data-angry="4" data-happy="0" data-sad="0" data-rank="95" data-hasmaxattribute="False" data-year="1971"}
**Album:** *Warum geht es mir so dreckig?* (1971)\
**Genres:** Proto-Punk
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"><span class="badge bg-primary rounded-pill">Anti-fascist Anthem</span></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Angry</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #FF5D45FF; width:80.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Groovy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #9C6B4EFF; width:20.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Passion</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #A463F2FF; width:40.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="WTE28YU_FrY"></lite-youtube></div></details>
## 94. Art Blakey & The Jazz Messengers - Moanin’{.song data-passion="0" data-dreamy="0" data-dark="0" data-groovy="2" data-angry="0" data-happy="2" data-sad="0" data-rank="94" data-hasmaxattribute="False" data-year="1959"}
**Album:** *Moanin’* (1959)\
**Genres:** Hard Bop
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Happy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #6CC5B0FF; width:40.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Groovy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #9C6B4EFF; width:40.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="Cv9NSR-2DwM"></lite-youtube></div></details>
## 93. Idles - Danny Nedelko{.song data-passion="2" data-dreamy="0" data-dark="0" data-groovy="0" data-angry="1" data-happy="4" data-sad="0" data-rank="93" data-hasmaxattribute="False" data-year="2018"}
**Album:** *Joy as an Act of Resistance. * (2018)\
**Genres:** Post-Punk
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"><span class="badge bg-primary rounded-pill">Anti-fascist Anthem</span></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Angry</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #FF5D45FF; width:20.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Happy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #6CC5B0FF; width:80.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Passion</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #A463F2FF; width:40.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="QkF_G-RF66M"></lite-youtube></div></details>
## 92. Pulp - Common People{.song data-passion="3" data-dreamy="0" data-dark="0" data-groovy="0" data-angry="1" data-happy="0" data-sad="2" data-rank="92" data-hasmaxattribute="False" data-year="1995"}
**Album:** *Different Class* (1995)\
**Genres:** Britpop
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Sad</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #4269D0FF; width:40.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Angry</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #FF5D45FF; width:20.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Passion</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #A463F2FF; width:60.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="yuTMWgOduFM"></lite-youtube></div></details>
## 91. Aretha Franklin - I Say a Little Prayer{.song data-passion="3" data-dreamy="0" data-dark="0" data-groovy="0" data-angry="0" data-happy="3" data-sad="0" data-rank="91" data-hasmaxattribute="False" data-year="1968"}
**Album:** *Aretha Now* (1968)\
**Genres:** Southern Soul
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Happy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #6CC5B0FF; width:60.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Passion</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #A463F2FF; width:60.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="TDyiREoBw0o"></lite-youtube></div></details>
## 90. Ryuichi Sakamoto - Thousand Knives{.song data-passion="0" data-dreamy="0" data-dark="0" data-groovy="4" data-angry="0" data-happy="1" data-sad="0" data-rank="90" data-hasmaxattribute="False" data-year="1978"}
**Album:** *Thousand Knives of Ryuichi Sakamoto * (1978)\
**Genres:** Progressive Electronic
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"><span class="badge bg-primary rounded-pill">Instrumental</span></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Happy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #6CC5B0FF; width:20.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Groovy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #9C6B4EFF; width:80.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="IKz0NNemy8M"></lite-youtube></div></details>
## 89. Jessie Ware - Spotlight{.song data-passion="0" data-dreamy="2" data-dark="0" data-groovy="3" data-angry="0" data-happy="0" data-sad="1" data-rank="89" data-hasmaxattribute="False" data-year="2020"}
**Album:** *What’s Your Pleasure* (2020)\
**Genres:** Dance-Pop
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Sad</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #4269D0FF; width:20.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Groovy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #9C6B4EFF; width:60.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dreamy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #F0BD3CFF; width:40.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="kw56LGfrf4A"></lite-youtube></div></details>
## 88. Kate Bush - Wuthering Heights{.song data-passion="4" data-dreamy="0" data-dark="0" data-groovy="0" data-angry="0" data-happy="1" data-sad="3" data-rank="88" data-hasmaxattribute="False" data-year="1978"}
**Album:** *The Kick Inside* (1978)\
**Genres:** Art Pop
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Sad</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #4269D0FF; width:60.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Happy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #6CC5B0FF; width:20.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Passion</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #A463F2FF; width:80.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="Fk-4lXLM34g"></lite-youtube></div></details>
## 87. Tyler, the Creator - EARFQUAKE{.song data-passion="2" data-dreamy="0" data-dark="0" data-groovy="0" data-angry="0" data-happy="0" data-sad="3" data-rank="87" data-hasmaxattribute="False" data-year="2019"}
**Album:** *Igor* (2019)\
**Genres:** Neo-Soul
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"><span class="badge bg-primary rounded-pill">🔥 Music Video</span></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Sad</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #4269D0FF; width:60.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Passion</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #A463F2FF; width:40.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="HmAsUQEFYGI"></lite-youtube></div></details>
## 86. Car Seat Headrest - Beach Life-In-Death{.song data-passion="4" data-dreamy="0" data-dark="0" data-groovy="0" data-angry="1" data-happy="0" data-sad="3" data-rank="86" data-hasmaxattribute="False" data-year="2018"}
**Album:** *Twin Fantasy* (2018)\
**Genres:** Indie Rock
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Sad</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #4269D0FF; width:60.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Angry</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #FF5D45FF; width:20.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Passion</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #A463F2FF; width:80.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="hx59YVs5itM"></lite-youtube></div></details>
## 85. Isaac Hayes - Walk on By{.song data-passion="0" data-dreamy="1" data-dark="0" data-groovy="0" data-angry="0" data-happy="0" data-sad="3" data-rank="85" data-hasmaxattribute="False" data-year="1969"}
**Album:** *Hot Buttered Soul* (1969)\
**Genres:** Progressive Soul
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Sad</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #4269D0FF; width:60.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dreamy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #F0BD3CFF; width:20.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="DFdR2LLM3bY"></lite-youtube></div></details>
## 84. Swans - Love Will Save You{.song data-passion="0" data-dreamy="0" data-dark="3" data-groovy="0" data-angry="0" data-happy="0" data-sad="4" data-rank="84" data-hasmaxattribute="False" data-year="1991"}
**Album:** *White Light from the Mouth of Infinity* (1991)\
**Genres:** Gothic Rock
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Sad</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #4269D0FF; width:80.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dark</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #1B1B1BFF; width:60.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="HXbcErP-Xok"></lite-youtube></div></details>
## 83. Phoebe Bridgers - I Know the End{.song data-passion="2" data-dreamy="1" data-dark="2" data-groovy="0" data-angry="0" data-happy="0" data-sad="4" data-rank="83" data-hasmaxattribute="False" data-year="2020"}
**Album:** *Punisher* (2020)\
**Genres:** Singer-Songwriter
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Sad</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #4269D0FF; width:80.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dark</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #1B1B1BFF; width:40.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dreamy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #F0BD3CFF; width:20.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Passion</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #A463F2FF; width:40.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="WJ9-xN6dCW4"></lite-youtube></div></details>
## 82. Gris - Il était une forêt{.song data-passion="3" data-dreamy="0" data-dark="5" data-groovy="0" data-angry="0" data-happy="0" data-sad="3" data-rank="82" data-hasmaxattribute="True" data-year="2007"}
**Album:** *Il était une forêt* (2007)\
**Genres:** Depressive Black Metal
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Sad</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #4269D0FF; width:60.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dark</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #1B1B1BFF; width:100.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Passion</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #A463F2FF; width:60.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="rMrBWwEMA7w"></lite-youtube></div></details>
## 81. Barbara Dane - Resistance Hymn{.song data-passion="2" data-dreamy="0" data-dark="0" data-groovy="0" data-angry="1" data-happy="1" data-sad="1" data-rank="81" data-hasmaxattribute="False" data-year="1970"}
**Album:** *FTA!: Songs of the GI Resistance * (1970)\
**Genres:** Contemporary Folk
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"><span class="badge bg-primary rounded-pill">Anti-fascist Anthem</span><span class="badge bg-primary rounded-pill">🏆 Least Views: 10k</span></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Sad</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #4269D0FF; width:20.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Angry</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #FF5D45FF; width:20.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Happy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #6CC5B0FF; width:20.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Passion</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #A463F2FF; width:40.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="YS1rSEnxgNE"></lite-youtube></div></details>
## 80. Ninajirachi - Infohazard{.song data-passion="0" data-dreamy="3" data-dark="2" data-groovy="0" data-angry="0" data-happy="1" data-sad="1" data-rank="80" data-hasmaxattribute="False" data-year="2025"}
**Album:** *I Love My Computer * (2025)\
**Genres:** Trance
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Sad</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #4269D0FF; width:20.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Happy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #6CC5B0FF; width:20.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dark</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #1B1B1BFF; width:40.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dreamy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #F0BD3CFF; width:60.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="p2ZdeIKJA8c"></lite-youtube></div></details>
## 79. Vangelis - Memories of Green{.song data-passion="0" data-dreamy="4" data-dark="0" data-groovy="0" data-angry="0" data-happy="0" data-sad="4" data-rank="79" data-hasmaxattribute="False" data-year="1980"}
**Album:** *Blade Runner* (1980)\
**Genres:** Progressive Electronic
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"><span class="badge bg-primary rounded-pill">Soundtrack</span></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Sad</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #4269D0FF; width:80.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dreamy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #F0BD3CFF; width:80.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="u1KfOMkyU_w"></lite-youtube></div></details>
## 78. Beach House - Myth{.song data-passion="1" data-dreamy="5" data-dark="0" data-groovy="0" data-angry="0" data-happy="0" data-sad="3" data-rank="78" data-hasmaxattribute="True" data-year="2012"}
**Album:** *Bloom* (2012)\
**Genres:** Dream Pop
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Sad</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #4269D0FF; width:60.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dreamy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #F0BD3CFF; width:100.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Passion</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #A463F2FF; width:20.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="FuvWc3ToDHg"></lite-youtube></div></details>
## 77. Lily Chou-Chou - Arabesque{.song data-passion="0" data-dreamy="3" data-dark="0" data-groovy="0" data-angry="0" data-happy="0" data-sad="5" data-rank="77" data-hasmaxattribute="True" data-year="2001"}
**Album:** *Kokyuu* (2001)\
**Genres:** Ambient Pop
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"><span class="badge bg-primary rounded-pill">Soundtrack</span></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Sad</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #4269D0FF; width:100.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dreamy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #F0BD3CFF; width:60.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="12mwzwUL7Vk"></lite-youtube></div></details>
## 76. Kessoku Band - Karakara{.song data-passion="1" data-dreamy="1" data-dark="0" data-groovy="0" data-angry="0" data-happy="3" data-sad="0" data-rank="76" data-hasmaxattribute="False" data-year="2022"}
**Album:** *Kessoku Band* (2022)\
**Genres:** Shimokita-kei
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Happy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #6CC5B0FF; width:60.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dreamy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #F0BD3CFF; width:20.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Passion</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #A463F2FF; width:20.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="IwHwv-lcxi4"></lite-youtube></div></details>
## 75. Sewerslvt - Looming.Sorrow.Decent{.song data-passion="0" data-dreamy="0" data-dark="3" data-groovy="3" data-angry="3" data-happy="0" data-sad="1" data-rank="75" data-hasmaxattribute="False" data-year="2021"}
**Album:** *Skitzofrenia Simulation* (2021)\
**Genres:** Atmospheric Drum’n’Bass
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Sad</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #4269D0FF; width:20.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Angry</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #FF5D45FF; width:60.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dark</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #1B1B1BFF; width:60.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Groovy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #9C6B4EFF; width:60.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="x1P_0mUsBJ0"></lite-youtube></div></details>
## 74. Lorien Testard - Alicia{.song data-passion="3" data-dreamy="1" data-dark="1" data-groovy="0" data-angry="0" data-happy="0" data-sad="4" data-rank="74" data-hasmaxattribute="False" data-year="2025"}
**Album:** *Clair Obscur: Expedition 33 * (2025)\
**Genres:** Classical Crossover
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"><span class="badge bg-primary rounded-pill">Soundtrack</span></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Sad</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #4269D0FF; width:80.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dark</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #1B1B1BFF; width:20.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dreamy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #F0BD3CFF; width:20.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Passion</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #A463F2FF; width:60.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="yakOBIoyoik"></lite-youtube></div></details>
## 73. Kendrick Lamar - Alright{.song data-passion="2" data-dreamy="0" data-dark="1" data-groovy="1" data-angry="2" data-happy="3" data-sad="0" data-rank="73" data-hasmaxattribute="False" data-year="2015"}
**Album:** *To Pimp a Butterfly* (2015)\
**Genres:** West Coast Hip Hop
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Angry</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #FF5D45FF; width:40.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Happy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #6CC5B0FF; width:60.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dark</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #1B1B1BFF; width:20.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Groovy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #9C6B4EFF; width:20.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Passion</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #A463F2FF; width:40.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="Z-48u_uWMHY"></lite-youtube></div></details>
## 72. Nina Simone - Sinnerman{.song data-passion="4" data-dreamy="0" data-dark="2" data-groovy="0" data-angry="3" data-happy="0" data-sad="0" data-rank="72" data-hasmaxattribute="False" data-year="1965"}
**Album:** *Pastel Blues* (1965)\
**Genres:** Rhythm & Blues
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Angry</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #FF5D45FF; width:60.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dark</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #1B1B1BFF; width:40.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Passion</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #A463F2FF; width:80.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="QH3Fx41Jpl4"></lite-youtube></div></details>
## 71. My Bloody Valentine - when you sleep{.song data-passion="0" data-dreamy="5" data-dark="0" data-groovy="0" data-angry="0" data-happy="2" data-sad="2" data-rank="71" data-hasmaxattribute="True" data-year="1991"}
**Album:** *Loveless* (1991)\
**Genres:** Shoegaze
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Sad</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #4269D0FF; width:40.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Happy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #6CC5B0FF; width:40.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dreamy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #F0BD3CFF; width:100.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="BJLcbj80Ka8"></lite-youtube></div></details>
## 70. Bob Dylan - Shelter from the Storm{.song data-passion="0" data-dreamy="0" data-dark="0" data-groovy="0" data-angry="0" data-happy="2" data-sad="3" data-rank="70" data-hasmaxattribute="False" data-year="1975"}
**Album:** *Blood on the Tracks* (1975)\
**Genres:** Singer-Songwriter
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Sad</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #4269D0FF; width:60.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Happy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #6CC5B0FF; width:40.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="IzaXlq1Pdmk"></lite-youtube></div></details>
## 69. Panopticon - Dead Loons{.song data-passion="3" data-dreamy="0" data-dark="2" data-groovy="0" data-angry="3" data-happy="0" data-sad="3" data-rank="69" data-hasmaxattribute="False" data-year="2021"}
**Album:** *...And Again Into the Light* (2021)\
**Genres:** Atmospheric Black Metal
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Sad</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #4269D0FF; width:60.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Angry</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #FF5D45FF; width:60.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dark</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #1B1B1BFF; width:40.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Passion</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #A463F2FF; width:60.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="3SGscxQfmc4"></lite-youtube></div></details>
## 68. Sharon Van Etten & Angel Olsen  - Like I Used To{.song data-passion="4" data-dreamy="1" data-dark="0" data-groovy="0" data-angry="0" data-happy="0" data-sad="2" data-rank="68" data-hasmaxattribute="False" data-year="2021"}
**Album:** *Like I Used To (Single)* (2021)\
**Genres:** Heartland Rock
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Sad</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #4269D0FF; width:40.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dreamy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #F0BD3CFF; width:20.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Passion</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #A463F2FF; width:80.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="5ibj87fwRaM"></lite-youtube></div></details>
## 67. Camellia - Together forever, my lovely video game cartridges{.song data-passion="0" data-dreamy="0" data-dark="0" data-groovy="3" data-angry="0" data-happy="6" data-sad="0" data-rank="67" data-hasmaxattribute="True" data-year="2018"}
**Album:** *Heart of Android* (2018)\
**Genres:** Electrohouse
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"><span class="badge bg-primary rounded-pill">🏆 Happiest Song</span></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Happy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #6CC5B0FF; width:100.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Groovy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #9C6B4EFF; width:60.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="9xeZRQDKmLE"></lite-youtube></div></details>
## 66. Deftones - Sextape{.song data-passion="3" data-dreamy="4" data-dark="0" data-groovy="0" data-angry="0" data-happy="2" data-sad="0" data-rank="66" data-hasmaxattribute="False" data-year="2010"}
**Album:** *Diamond Eyes* (2010)\
**Genres:** Dream Pop
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"><span class="badge bg-primary rounded-pill">❤️ Music Video</span></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Happy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #6CC5B0FF; width:40.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dreamy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #F0BD3CFF; width:80.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Passion</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #A463F2FF; width:60.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="f0pdwd0miqs"></lite-youtube></div><br>
Contender for most sensual song. This, together with half of FKA Twigs’s discography.
</details>
## 65. Tim Hecker - Borderlands{.song data-passion="0" data-dreamy="4" data-dark="2" data-groovy="0" data-angry="0" data-happy="0" data-sad="4" data-rank="65" data-hasmaxattribute="False" data-year="2009"}
**Album:** *An Imaginary Country* (2009)\
**Genres:** Ambient
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"><span class="badge bg-primary rounded-pill">Instrumental</span></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Sad</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #4269D0FF; width:80.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dark</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #1B1B1BFF; width:40.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dreamy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #F0BD3CFF; width:80.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="LIJEmC91inA"></lite-youtube></div></details>
## 64. Tom Waits - Come On Up to the House{.song data-passion="0" data-dreamy="0" data-dark="0" data-groovy="0" data-angry="0" data-happy="3" data-sad="3" data-rank="64" data-hasmaxattribute="False" data-year="1999"}
**Album:** *Mule Variations* (1999)\
**Genres:** Singer-Songwriter
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Sad</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #4269D0FF; width:60.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Happy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #6CC5B0FF; width:60.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="wFrqclcm8pU"></lite-youtube></div></details>
## 63. Fairouz - Al Bosta{.song data-passion="3" data-dreamy="0" data-dark="0" data-groovy="2" data-angry="0" data-happy="0" data-sad="1" data-rank="63" data-hasmaxattribute="False" data-year="1979"}
**Album:** *Wahdon* (1979)\
**Genres:** Jazz-Funk
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Sad</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #4269D0FF; width:20.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Groovy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #9C6B4EFF; width:40.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Passion</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #A463F2FF; width:60.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="VrJnhLmwzbU"></lite-youtube></div></details>
## 62. Uchu Conbini - 8films/tobira{.song data-passion="0" data-dreamy="4" data-dark="0" data-groovy="0" data-angry="0" data-happy="1" data-sad="2" data-rank="62" data-hasmaxattribute="False" data-year="2013"}
**Album:** *Somaru oto wo kakunin shitara* (2013)\
**Genres:** Math Pop
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Sad</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #4269D0FF; width:40.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Happy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #6CC5B0FF; width:20.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dreamy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #F0BD3CFF; width:80.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="XWqua6rsEmw"></lite-youtube></div></details>
## 61. Ado - Where the Wind Blows{.song data-passion="4" data-dreamy="0" data-dark="0" data-groovy="0" data-angry="0" data-happy="2" data-sad="3" data-rank="61" data-hasmaxattribute="False" data-year="2022"}
**Album:** *Uta's Songs One Piece Film Red* (2022)\
**Genres:** Classical Crossover
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"><span class="badge bg-primary rounded-pill">🏆 Best Music Video</span></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Sad</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #4269D0FF; width:60.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Happy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #6CC5B0FF; width:40.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Passion</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #A463F2FF; width:80.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="YO-rXgQKlF8"></lite-youtube></div><br>
My favorite music video of all time! Director Megumi Ishitani is a generational talent and her storyboards are pure works of art.
</details>
## 60. kurayamisaka - Cinema Paradiso{.song data-passion="1" data-dreamy="4" data-dark="0" data-groovy="0" data-angry="0" data-happy="1" data-sad="1" data-rank="60" data-hasmaxattribute="False" data-year="2022"}
**Album:** *Kimi Wo Omotte Iru* (2022)\
**Genres:** Shoegaze
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Sad</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #4269D0FF; width:20.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Happy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #6CC5B0FF; width:20.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dreamy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #F0BD3CFF; width:80.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Passion</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #A463F2FF; width:20.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="EN0VVHgaJxg"></lite-youtube></div></details>
## 59. Hannes Wader - Leben einzeln und frei{.song data-passion="1" data-dreamy="0" data-dark="0" data-groovy="0" data-angry="1" data-happy="3" data-sad="0" data-rank="59" data-hasmaxattribute="False" data-year="1982"}
**Album:** *Daß nichts bleibt wie es war * (1982)\
**Genres:** Liedermacher
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Angry</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #FF5D45FF; width:20.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Happy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #6CC5B0FF; width:60.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Passion</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #A463F2FF; width:20.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="fKB866ZTI18"></lite-youtube></div></details>
## 58. Iron Maiden - Run to the Hills{.song data-passion="4" data-dreamy="0" data-dark="0" data-groovy="0" data-angry="2" data-happy="0" data-sad="0" data-rank="58" data-hasmaxattribute="False" data-year="1982"}
**Album:** *The Number of the Beast* (1982)\
**Genres:** Heavy Metal
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Angry</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #FF5D45FF; width:40.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Passion</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #A463F2FF; width:80.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="86URGgqONvA"></lite-youtube></div></details>
## 57. World of Pleasure - Domination 2{.song data-passion="0" data-dreamy="0" data-dark="2" data-groovy="1" data-angry="7" data-happy="0" data-sad="0" data-rank="57" data-hasmaxattribute="True" data-year="2022"}
**Album:** *World of Pleasure & Friends * (2022)\
**Genres:** Metalcore
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"><span class="badge bg-primary rounded-pill">🏆 Most Pissed Off Song</span></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Angry</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #FF5D45FF; width:100.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dark</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #1B1B1BFF; width:40.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Groovy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #9C6B4EFF; width:20.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="z1WiJrJtwNg"></lite-youtube></div></details>
## 56. Ichiko Aoba - A Hill of the Moon{.song data-passion="0" data-dreamy="3" data-dark="0" data-groovy="0" data-angry="0" data-happy="4" data-sad="0" data-rank="56" data-hasmaxattribute="False" data-year="2018"}
**Album:** *qp* (2018)\
**Genres:** Singer-Songwriter
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"><span class="badge bg-primary rounded-pill">Seen Live</span></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Happy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #6CC5B0FF; width:80.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dreamy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #F0BD3CFF; width:60.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="ske5X_BLr1I"></lite-youtube></div></details>
## 55. Emperor - Ye Entrancemperium {.song data-passion="0" data-dreamy="0" data-dark="4" data-groovy="0" data-angry="4" data-happy="0" data-sad="0" data-rank="55" data-hasmaxattribute="False" data-year="1997"}
**Album:** *Anthems to the Welkin at Dusk* (1997)\
**Genres:** Symphonic Black Metal
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"><span class="badge bg-primary rounded-pill">⚠️ Sketchy Artist</span></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Angry</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #FF5D45FF; width:80.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dark</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #1B1B1BFF; width:80.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="9mfpOa0Znr8"></lite-youtube></div></details>
## 54. Stevie Wonder - Sir Duke{.song data-passion="3" data-dreamy="0" data-dark="0" data-groovy="4" data-angry="0" data-happy="5" data-sad="0" data-rank="54" data-hasmaxattribute="True" data-year="1976"}
**Album:** *Songs in the Key of Life* (1976)\
**Genres:** Pop Soul
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Happy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #6CC5B0FF; width:100.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Groovy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #9C6B4EFF; width:80.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Passion</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #A463F2FF; width:60.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="EnNgASBdCeo"></lite-youtube></div></details>
## 53. The Blue Hearts - Owaranai Uta{.song data-passion="3" data-dreamy="0" data-dark="0" data-groovy="0" data-angry="1" data-happy="4" data-sad="1" data-rank="53" data-hasmaxattribute="False" data-year="1987"}
**Album:** *The Blue Hearts* (1987)\
**Genres:** Pop Punk
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Sad</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #4269D0FF; width:20.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Angry</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #FF5D45FF; width:20.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Happy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #6CC5B0FF; width:80.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Passion</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #A463F2FF; width:60.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="laRZR6AUvaU"></lite-youtube></div></details>
## 52. Weyes Blood - Andromeda{.song data-passion="1" data-dreamy="4" data-dark="0" data-groovy="0" data-angry="0" data-happy="0" data-sad="3" data-rank="52" data-hasmaxattribute="False" data-year="2019"}
**Album:** *Titanic Rising* (2019)\
**Genres:** Psychedelic Pop
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Sad</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #4269D0FF; width:60.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dreamy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #F0BD3CFF; width:80.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Passion</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #A463F2FF; width:20.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="ZHGw78IJryE"></lite-youtube></div></details>
## 51. Slayer - Angel of Death{.song data-passion="0" data-dreamy="0" data-dark="4" data-groovy="0" data-angry="4" data-happy="0" data-sad="0" data-rank="51" data-hasmaxattribute="False" data-year="1986"}
**Album:** *Reign in Blood* (1986)\
**Genres:** Thrash Metal
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Angry</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #FF5D45FF; width:80.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dark</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #1B1B1BFF; width:80.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="r7cWi41XGCM"></lite-youtube></div></details>
## 50. Marvin Gaye - What's Going On {.song data-passion="2" data-dreamy="1" data-dark="0" data-groovy="0" data-angry="0" data-happy="2" data-sad="3" data-rank="50" data-hasmaxattribute="False" data-year="1971"}
**Album:** *What's Going On* (1971)\
**Genres:** Smooth Soul
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Sad</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #4269D0FF; width:60.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Happy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #6CC5B0FF; width:40.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dreamy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #F0BD3CFF; width:20.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Passion</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #A463F2FF; width:40.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="H-kA3UtBj4M"></lite-youtube></div></details>
## 49. Ging Nang Boyz - Shounen Shoujo{.song data-passion="4" data-dreamy="1" data-dark="0" data-groovy="0" data-angry="0" data-happy="2" data-sad="3" data-rank="49" data-hasmaxattribute="False" data-year="2021"}
**Album:** *Shounen Shoujo* (2021)\
**Genres:** Seishun Punk
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Sad</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #4269D0FF; width:60.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Happy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #6CC5B0FF; width:40.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dreamy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #F0BD3CFF; width:20.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Passion</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #A463F2FF; width:80.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="7VYqcCLIx0s"></lite-youtube></div></details>
## 48. Lingua Ignota - DO YOU DOUBT ME TRAITOR{.song data-passion="0" data-dreamy="0" data-dark="7" data-groovy="0" data-angry="5" data-happy="0" data-sad="0" data-rank="48" data-hasmaxattribute="True" data-year="2019"}
**Album:** *Caligula* (2019)\
**Genres:** Neoclassical Darkwave
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"><span class="badge bg-primary rounded-pill">🏆 Most Insane Vocal Performance</span></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Angry</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #FF5D45FF; width:100.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dark</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #1B1B1BFF; width:100.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="8jma4fQfJGI"></lite-youtube></div></details>
## 47. Asian Kung-Fu Generation - Rock’n’Roll, Morning Light Falls on You{.song data-passion="1" data-dreamy="2" data-dark="0" data-groovy="0" data-angry="0" data-happy="2" data-sad="2" data-rank="47" data-hasmaxattribute="False" data-year="2008"}
**Album:** *World, World, World* (2008)\
**Genres:** Shimokita-kei
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Sad</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #4269D0FF; width:40.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Happy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #6CC5B0FF; width:40.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dreamy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #F0BD3CFF; width:40.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Passion</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #A463F2FF; width:20.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="rDTFSD9K9dA"></lite-youtube></div></details>
## 46. Opeth - Blackwater Park{.song data-passion="0" data-dreamy="1" data-dark="4" data-groovy="2" data-angry="2" data-happy="0" data-sad="1" data-rank="46" data-hasmaxattribute="False" data-year="2001"}
**Album:** *Blackwater Park* (2001)\
**Genres:** Progressive Metal
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Sad</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #4269D0FF; width:20.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Angry</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #FF5D45FF; width:40.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dark</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #1B1B1BFF; width:80.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Groovy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #9C6B4EFF; width:40.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dreamy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #F0BD3CFF; width:20.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="ngdaa4aZLgA"></lite-youtube></div></details>
## 45. Javiera Mena - Cámara lenta{.song data-passion="0" data-dreamy="4" data-dark="0" data-groovy="0" data-angry="0" data-happy="1" data-sad="0" data-rank="45" data-hasmaxattribute="False" data-year="2005"}
**Album:** *Esquemas juveniles* (2005)\
**Genres:** Indie Pop
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Happy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #6CC5B0FF; width:20.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dreamy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #F0BD3CFF; width:80.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="vN1AlIBob-o"></lite-youtube></div></details>
## 44. Parannoul - White Ceiling{.song data-passion="3" data-dreamy="5" data-dark="0" data-groovy="0" data-angry="1" data-happy="1" data-sad="3" data-rank="44" data-hasmaxattribute="True" data-year="2021"}
**Album:** *To See the Next Part of the Dream* (2021)\
**Genres:** Shoegaze
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Sad</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #4269D0FF; width:60.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Angry</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #FF5D45FF; width:20.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Happy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #6CC5B0FF; width:20.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dreamy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #F0BD3CFF; width:100.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Passion</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #A463F2FF; width:60.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="g1x1NtWGw5s"></lite-youtube></div></details>
## 43. System of a Down - Aerials{.song data-passion="1" data-dreamy="3" data-dark="0" data-groovy="0" data-angry="0" data-happy="0" data-sad="1" data-rank="43" data-hasmaxattribute="False" data-year="2001"}
**Album:** *Toxicity* (2001)\
**Genres:** Alternative Metal
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"><span class="badge bg-primary rounded-pill">🏆 Most Views: 547M</span></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Sad</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #4269D0FF; width:20.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dreamy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #F0BD3CFF; width:60.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Passion</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #A463F2FF; width:20.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="L-iepu3EtyE"></lite-youtube></div></details>
## 42. toe - Goodbye{.song data-passion="3" data-dreamy="3" data-dark="0" data-groovy="1" data-angry="0" data-happy="1" data-sad="3" data-rank="42" data-hasmaxattribute="False" data-year="2009"}
**Album:** *For Long Tomorrow* (2009)\
**Genres:** Midwest Emo
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"><span class="badge bg-primary rounded-pill">❤️ Music Video</span><span class="badge bg-primary rounded-pill">🏆 Best Drumming</span></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Sad</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #4269D0FF; width:60.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Happy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #6CC5B0FF; width:20.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Groovy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #9C6B4EFF; width:20.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dreamy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #F0BD3CFF; width:60.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Passion</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #A463F2FF; width:60.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="e1pZIfretEs"></lite-youtube></div><br>
I linked the music video above because it is genuinely amazing, but it only features an abridged version of the song. The full, superior version is 7-8 minutes long, see e.g. this [live peformance](https://www.youtube.com/watch?v=azSsMG6h8k0).
</details>
## 41. Sea Power - Red Rock Riviera{.song data-passion="0" data-dreamy="1" data-dark="0" data-groovy="0" data-angry="0" data-happy="0" data-sad="3" data-rank="41" data-hasmaxattribute="False" data-year="2013"}
**Album:** *From the Sea to the Land Beyond* (2013)\
**Genres:** Post-Rock
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Sad</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #4269D0FF; width:60.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dreamy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #F0BD3CFF; width:20.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="NSkb5OtTmgg"></lite-youtube></div></details>
## 40. Judas Priest - Painkiller{.song data-passion="3" data-dreamy="0" data-dark="0" data-groovy="0" data-angry="3" data-happy="0" data-sad="0" data-rank="40" data-hasmaxattribute="False" data-year="1990"}
**Album:** *Painkiller* (1990)\
**Genres:** Speed Metal
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Angry</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #FF5D45FF; width:60.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Passion</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #A463F2FF; width:60.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="kO_EdmtR5Ck"></lite-youtube></div></details>
## 39. Mass of the Fermenting Dregs - Delusionalism{.song data-passion="3" data-dreamy="0" data-dark="0" data-groovy="0" data-angry="0" data-happy="1" data-sad="1" data-rank="39" data-hasmaxattribute="False" data-year="2006"}
**Album:** *Mass of the Fermenting Dregs* (2006)\
**Genres:** Shimokita-kei
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"><span class="badge bg-primary rounded-pill">Seen Live</span></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Sad</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #4269D0FF; width:20.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Happy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #6CC5B0FF; width:20.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Passion</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #A463F2FF; width:60.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="5p_DvecvJKc"></lite-youtube></div></details>
## 38. Julee Cruise - Questions in a World of Blue{.song data-passion="0" data-dreamy="3" data-dark="1" data-groovy="0" data-angry="0" data-happy="0" data-sad="5" data-rank="38" data-hasmaxattribute="True" data-year="1992"}
**Album:** *Twin Peaks: Fire Walk with Me* (1992)\
**Genres:** Ambient Pop
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"><span class="badge bg-primary rounded-pill">Soundtrack</span></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Sad</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #4269D0FF; width:100.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dark</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #1B1B1BFF; width:20.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dreamy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #F0BD3CFF; width:60.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="MOSaLtcqob8"></lite-youtube></div></details>
## 37. Hikaru Utada - Beautiful World{.song data-passion="3" data-dreamy="3" data-dark="0" data-groovy="0" data-angry="0" data-happy="0" data-sad="2" data-rank="37" data-hasmaxattribute="False" data-year="2008"}
**Album:** *Heart Station* (2008)\
**Genres:** J-Pop
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Sad</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #4269D0FF; width:40.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dreamy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #F0BD3CFF; width:60.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Passion</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #A463F2FF; width:60.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="N2tSDKngeoY"></lite-youtube></div></details>
## 36. Carly Rae Jepsen - Run Away With Me{.song data-passion="3" data-dreamy="1" data-dark="0" data-groovy="0" data-angry="0" data-happy="4" data-sad="0" data-rank="36" data-hasmaxattribute="False" data-year="2015"}
**Album:** *E·MO·TION* (2015)\
**Genres:** Synthpop
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Happy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #6CC5B0FF; width:80.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dreamy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #F0BD3CFF; width:20.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Passion</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #A463F2FF; width:60.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="TeccAtqd5K8"></lite-youtube></div></details>
## 35. The Cure - Endsong{.song data-passion="0" data-dreamy="3" data-dark="4" data-groovy="0" data-angry="0" data-happy="0" data-sad="4" data-rank="35" data-hasmaxattribute="False" data-year="2024"}
**Album:** *Songs of a Lost World* (2024)\
**Genres:** Gothic Rock
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Sad</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #4269D0FF; width:80.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dark</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #1B1B1BFF; width:80.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dreamy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #F0BD3CFF; width:60.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="gA5pg7DRLf4"></lite-youtube></div></details>
## 34. Ling Tosite Sigure - This Is Is This?{.song data-passion="5" data-dreamy="2" data-dark="1" data-groovy="0" data-angry="2" data-happy="0" data-sad="2" data-rank="34" data-hasmaxattribute="True" data-year="2010"}
**Album:** *Still a Sigure Virgin? * (2010)\
**Genres:** Post-Hardcore
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"><span class="badge bg-primary rounded-pill">Emotional Rollercoaster</span></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Sad</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #4269D0FF; width:40.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Angry</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #FF5D45FF; width:40.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dark</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #1B1B1BFF; width:20.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dreamy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #F0BD3CFF; width:40.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Passion</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #A463F2FF; width:100.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="kP03KZyUxaU"></lite-youtube></div></details>
## 33. supercell - Kimi no shiranai monogatari{.song data-passion="2" data-dreamy="0" data-dark="0" data-groovy="0" data-angry="0" data-happy="5" data-sad="3" data-rank="33" data-hasmaxattribute="True" data-year="2011"}
**Album:** *Today Is a Beautiful Day* (2011)\
**Genres:** Pop Rock
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Sad</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #4269D0FF; width:60.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Happy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #6CC5B0FF; width:100.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Passion</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #A463F2FF; width:40.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="0VpGoDp3FCE"></lite-youtube></div></details>
## 32. Snapcase - Guilty by Ignorance{.song data-passion="0" data-dreamy="0" data-dark="0" data-groovy="1" data-angry="5" data-happy="0" data-sad="0" data-rank="32" data-hasmaxattribute="True" data-year="1997"}
**Album:** *Progression Through Unlearning* (1997)\
**Genres:** Metalcore
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"><span class="badge bg-primary rounded-pill">Anti-fascist Anthem</span></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Angry</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #FF5D45FF; width:100.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Groovy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #9C6B4EFF; width:20.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="wb1byFx1wAk"></lite-youtube></div></details>
## 31. My Chemical Romance - Helena{.song data-passion="4" data-dreamy="0" data-dark="1" data-groovy="0" data-angry="1" data-happy="0" data-sad="2" data-rank="31" data-hasmaxattribute="False" data-year="2004"}
**Album:** *Three Cheers for Sweet Revenge* (2004)\
**Genres:** Emo-Pop
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Sad</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #4269D0FF; width:40.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Angry</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #FF5D45FF; width:20.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dark</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #1B1B1BFF; width:20.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Passion</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #A463F2FF; width:80.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="UCCyoocDxBA"></lite-youtube></div></details>
## 30. Sun Kil Moon - Duk Koo Kim{.song data-passion="0" data-dreamy="3" data-dark="0" data-groovy="0" data-angry="0" data-happy="1" data-sad="4" data-rank="30" data-hasmaxattribute="False" data-year="2003"}
**Album:** *Ghosts of the Great Highway* (2003)\
**Genres:** Slowcore
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"><span class="badge bg-primary rounded-pill">⚠️ Sketchy Artist</span><span class="badge bg-primary rounded-pill">🏆 Longest: 14:33</span></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Sad</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #4269D0FF; width:80.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Happy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #6CC5B0FF; width:20.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dreamy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #F0BD3CFF; width:60.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="8-RjqU3T2x4"></lite-youtube></div></details>
## 29. Konstantin Wecker - Willy{.song data-passion="4" data-dreamy="0" data-dark="0" data-groovy="0" data-angry="2" data-happy="0" data-sad="3" data-rank="29" data-hasmaxattribute="False" data-year="1977"}
**Album:** *Genug ist nicht genug* (1977)\
**Genres:** Piano Blues
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"><span class="badge bg-primary rounded-pill">Anti-fascist Anthem</span></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Sad</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #4269D0FF; width:60.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Angry</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #FF5D45FF; width:40.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Passion</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #A463F2FF; width:80.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="mw6nD98IGwg"></lite-youtube></div></details>
## 28. Cameron Winter - $0.00{.song data-passion="4" data-dreamy="0" data-dark="0" data-groovy="0" data-angry="0" data-happy="0" data-sad="4" data-rank="28" data-hasmaxattribute="False" data-year="2024"}
**Album:** *Heavy Metal* (2024)\
**Genres:** Singer-Songwriter
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Sad</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #4269D0FF; width:80.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Passion</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #A463F2FF; width:80.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="ETZKZzz7MWo"></lite-youtube></div></details>
## 27. Portishead - Glory Box{.song data-passion="1" data-dreamy="4" data-dark="1" data-groovy="0" data-angry="0" data-happy="0" data-sad="2" data-rank="27" data-hasmaxattribute="False" data-year="1994"}
**Album:** *Dummy* (1994)\
**Genres:** Trip Hop
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Sad</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #4269D0FF; width:40.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dark</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #1B1B1BFF; width:20.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dreamy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #F0BD3CFF; width:80.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Passion</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #A463F2FF; width:20.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="c417rIku6Iw"></lite-youtube></div></details>
## 26. Radiohead - Weird Fishes/Arpeggi{.song data-passion="1" data-dreamy="5" data-dark="0" data-groovy="0" data-angry="0" data-happy="0" data-sad="2" data-rank="26" data-hasmaxattribute="True" data-year="2008"}
**Album:** *In Rainbows* (2008)\
**Genres:** Dream Pop
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"><span class="badge bg-primary rounded-pill">❤️ Music Video</span><span class="badge bg-primary rounded-pill">⚠️ Sketchy Artist</span></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Sad</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #4269D0FF; width:40.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dreamy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #F0BD3CFF; width:100.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Passion</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #A463F2FF; width:20.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="OIdrE5igo-k"></lite-youtube></div></details>
## 25. Rolo Tomassi - A Flood of Light{.song data-passion="4" data-dreamy="3" data-dark="1" data-groovy="0" data-angry="3" data-happy="2" data-sad="3" data-rank="25" data-hasmaxattribute="False" data-year="2018"}
**Album:** *Time Will Die and Love Will Bury It * (2018)\
**Genres:** Post-Metal
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"><span class="badge bg-primary rounded-pill">Emotional Rollercoaster</span></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Sad</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #4269D0FF; width:60.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Angry</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #FF5D45FF; width:60.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Happy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #6CC5B0FF; width:40.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dark</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #1B1B1BFF; width:20.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dreamy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #F0BD3CFF; width:60.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Passion</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #A463F2FF; width:80.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="hM_4Ty_ZHaU"></lite-youtube></div></details>
## 24. Fela Anikulapo Kuti and Afrika 70 - Zombie{.song data-passion="0" data-dreamy="0" data-dark="0" data-groovy="4" data-angry="1" data-happy="0" data-sad="0" data-rank="24" data-hasmaxattribute="False" data-year="1977"}
**Album:** *Zombie* (1977)\
**Genres:** Afrobeat
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"><span class="badge bg-primary rounded-pill">Anti-fascist Anthem</span></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Angry</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #FF5D45FF; width:20.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Groovy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #9C6B4EFF; width:80.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="Qj5x6pbJMyU"></lite-youtube></div></details>
## 23. Lana Del Rey - Venice Bitch{.song data-passion="0" data-dreamy="4" data-dark="0" data-groovy="0" data-angry="0" data-happy="0" data-sad="2" data-rank="23" data-hasmaxattribute="False" data-year="2018"}
**Album:** *Norman Fucking Rockwell!* (2018)\
**Genres:** Art Pop
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Sad</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #4269D0FF; width:40.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dreamy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #F0BD3CFF; width:80.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="Qg3DxELVPj4"></lite-youtube></div></details>
## 22. Keiichi Okabe - City Ruins (Rays of Light){.song data-passion="0" data-dreamy="4" data-dark="0" data-groovy="0" data-angry="0" data-happy="2" data-sad="4" data-rank="22" data-hasmaxattribute="False" data-year="2017"}
**Album:** *NieR:Automata * (2017)\
**Genres:** New Age
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"><span class="badge bg-primary rounded-pill">Soundtrack</span></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Sad</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #4269D0FF; width:80.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Happy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #6CC5B0FF; width:40.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dreamy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #F0BD3CFF; width:80.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="LC5HsZt4oNc"></lite-youtube></div></details>
## 21. Perfume - Dream Fighter{.song data-passion="1" data-dreamy="0" data-dark="0" data-groovy="0" data-angry="0" data-happy="5" data-sad="0" data-rank="21" data-hasmaxattribute="True" data-year="2008"}
**Album:** *⊿ (Triangle)* (2008)\
**Genres:** Electropop
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Happy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #6CC5B0FF; width:100.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Passion</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #A463F2FF; width:20.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="rBX5YGPNDbs"></lite-youtube></div></details>
## 20. The Dead Kennedys - Nazi Punks Fuck Off{.song data-passion="0" data-dreamy="0" data-dark="0" data-groovy="0" data-angry="5" data-happy="0" data-sad="0" data-rank="20" data-hasmaxattribute="True" data-year="1981"}
**Album:** *In God We Trust, Inc.* (1981)\
**Genres:** Hardcore Punk
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"><span class="badge bg-primary rounded-pill">Anti-fascist Anthem</span><span class="badge bg-primary rounded-pill">🏆 Shortest: 02:10</span></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Angry</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #FF5D45FF; width:100.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="PzHLPnGuVSQ"></lite-youtube></div></details>
## 19. Nas - N.Y. State of Mind{.song data-passion="0" data-dreamy="0" data-dark="2" data-groovy="1" data-angry="0" data-happy="0" data-sad="0" data-rank="19" data-hasmaxattribute="False" data-year="1994"}
**Album:** *Illmatic* (1994)\
**Genres:** Boom Bap
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dark</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #1B1B1BFF; width:40.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Groovy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #9C6B4EFF; width:20.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="izhKFB0_2w0"></lite-youtube></div></details>
## 18. Rage Against the Machine - Killing in the Name{.song data-passion="0" data-dreamy="0" data-dark="0" data-groovy="3" data-angry="4" data-happy="0" data-sad="0" data-rank="18" data-hasmaxattribute="False" data-year="1992"}
**Album:** *Rage Against the Machine* (1992)\
**Genres:** Alternative Metal
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"><span class="badge bg-primary rounded-pill">Anti-fascist Anthem</span></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Angry</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #FF5D45FF; width:80.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Groovy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #9C6B4EFF; width:60.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="bWXazVhlyxQ"></lite-youtube></div></details>
## 17. Electric Light Orchestra - Twilight{.song data-passion="3" data-dreamy="1" data-dark="0" data-groovy="1" data-angry="0" data-happy="3" data-sad="1" data-rank="17" data-hasmaxattribute="False" data-year="1981"}
**Album:** *Time* (1981)\
**Genres:** Pop Rock
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Sad</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #4269D0FF; width:20.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Happy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #6CC5B0FF; width:60.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Groovy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #9C6B4EFF; width:20.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dreamy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #F0BD3CFF; width:20.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Passion</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #A463F2FF; width:60.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="yDN68LxWW-8"></lite-youtube></div></details>
## 16. Gorguts - Le Toit Du Monde{.song data-passion="0" data-dreamy="0" data-dark="4" data-groovy="0" data-angry="4" data-happy="0" data-sad="0" data-rank="16" data-hasmaxattribute="False" data-year="2013"}
**Album:** *Colored Sands* (2013)\
**Genres:** Dissonant Death Metal
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Angry</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #FF5D45FF; width:80.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dark</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #1B1B1BFF; width:80.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="7LQd0IoJ25M"></lite-youtube></div></details>
## 15. Cocteau Twins - Heaven or Las Vegas {.song data-passion="1" data-dreamy="5" data-dark="0" data-groovy="0" data-angry="0" data-happy="0" data-sad="0" data-rank="15" data-hasmaxattribute="True" data-year="1990"}
**Album:** *Heaven or Las Vegas * (1990)\
**Genres:** Dream Pop
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dreamy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #F0BD3CFF; width:100.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Passion</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #A463F2FF; width:20.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="JlwcQR5HHck"></lite-youtube></div></details>
## 14. Seatbelts - Blue{.song data-passion="5" data-dreamy="2" data-dark="0" data-groovy="0" data-angry="0" data-happy="2" data-sad="3" data-rank="14" data-hasmaxattribute="True" data-year="1999"}
**Album:** *Cowboy Bebop Blue* (1999)\
**Genres:** Space Blues
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"><span class="badge bg-primary rounded-pill">Soundtrack</span></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Sad</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #4269D0FF; width:60.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Happy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #6CC5B0FF; width:40.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dreamy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #F0BD3CFF; width:40.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Passion</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #A463F2FF; width:100.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="Xjzb_-26m2o"></lite-youtube></div></details>
## 13. The Flaming Lips - Do You Realize??{.song data-passion="1" data-dreamy="2" data-dark="0" data-groovy="0" data-angry="0" data-happy="2" data-sad="3" data-rank="13" data-hasmaxattribute="False" data-year="2002"}
**Album:** *Yoshimi Battles the Pink Robots* (2002)\
**Genres:** Neo-Psychedelia
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"><span class="badge bg-primary rounded-pill">🏆 Most Beautiful Song</span></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Sad</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #4269D0FF; width:60.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Happy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #6CC5B0FF; width:40.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dreamy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #F0BD3CFF; width:40.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Passion</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #A463F2FF; width:20.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="lPXWt2ESxVY"></lite-youtube></div><br>
I made a [Studio Ghibli music video tribute](https://www.youtube.com/watch?v=nA2ypGM98h4) using this song and somehow it’s one of my proudest accomplishments.
</details>
## 12. The Pillows - Last Dinosaur{.song data-passion="3" data-dreamy="1" data-dark="0" data-groovy="0" data-angry="0" data-happy="3" data-sad="3" data-rank="12" data-hasmaxattribute="False" data-year="1999"}
**Album:** *Happy Bivouac* (1999)\
**Genres:** Power Pop
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Sad</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #4269D0FF; width:60.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Happy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #6CC5B0FF; width:60.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dreamy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #F0BD3CFF; width:20.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Passion</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #A463F2FF; width:60.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="xB2K-riHfSc"></lite-youtube></div></details>
## 11. Pink Floyd - Wish You Were Here{.song data-passion="0" data-dreamy="3" data-dark="0" data-groovy="0" data-angry="0" data-happy="0" data-sad="3" data-rank="11" data-hasmaxattribute="False" data-year="1975"}
**Album:** *Wish You Were Here* (1975)\
**Genres:** Art Rock
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Sad</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #4269D0FF; width:60.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dreamy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #F0BD3CFF; width:60.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="K6qj09OHvjw"></lite-youtube></div></details>
## 10. The Devin Townsend Band - Deadhead{.song data-passion="5" data-dreamy="3" data-dark="0" data-groovy="0" data-angry="1" data-happy="0" data-sad="2" data-rank="10" data-hasmaxattribute="True" data-year="2003"}
**Album:** *Accelerated Evolution* (2003)\
**Genres:** Progressive Metal
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Sad</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #4269D0FF; width:40.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Angry</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #FF5D45FF; width:20.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dreamy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #F0BD3CFF; width:60.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Passion</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #A463F2FF; width:100.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="tJz-L3SbrLE"></lite-youtube></div></details>
## 9. Kinoko Teikoku - Musician{.song data-passion="4" data-dreamy="4" data-dark="0" data-groovy="0" data-angry="0" data-happy="0" data-sad="4" data-rank="9" data-hasmaxattribute="False" data-year="2013"}
**Album:** *Eureka* (2013)\
**Genres:** Indie Rock
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Sad</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #4269D0FF; width:80.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dreamy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #F0BD3CFF; width:80.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Passion</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #A463F2FF; width:80.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="vA1Ph6SpTkI"></lite-youtube></div></details>
## 8. David Bowie - “Heroes”{.song data-passion="4" data-dreamy="1" data-dark="0" data-groovy="0" data-angry="0" data-happy="0" data-sad="3" data-rank="8" data-hasmaxattribute="False" data-year="1977"}
**Album:** *“Heroes”* (1977)\
**Genres:** Art Rock
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Sad</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #4269D0FF; width:60.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dreamy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #F0BD3CFF; width:20.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Passion</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #A463F2FF; width:80.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="YLp2cW7ICCU"></lite-youtube></div></details>
## 7. FKA Twigs - Cellophane{.song data-passion="5" data-dreamy="0" data-dark="0" data-groovy="0" data-angry="0" data-happy="0" data-sad="5" data-rank="7" data-hasmaxattribute="True" data-year="2019"}
**Album:** *Magdalene* (2019)\
**Genres:** Art Pop
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"><span class="badge bg-primary rounded-pill">❤️ Music Video</span></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Sad</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #4269D0FF; width:100.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Passion</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #A463F2FF; width:100.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="YkLjqFpBh84"></lite-youtube></div></details>
## 6. Shiina Ringo - Gips{.song data-passion="5" data-dreamy="0" data-dark="0" data-groovy="0" data-angry="1" data-happy="0" data-sad="2" data-rank="6" data-hasmaxattribute="True" data-year="2000"}
**Album:** *Shouso Strip* (2000)\
**Genres:** Shimokita-kei
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Sad</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #4269D0FF; width:40.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Angry</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #FF5D45FF; width:20.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Passion</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #A463F2FF; width:100.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="zldBTSx9JpE"></lite-youtube></div></details>
## 5. Converge - Jane Doe{.song data-passion="5" data-dreamy="0" data-dark="3" data-groovy="0" data-angry="5" data-happy="0" data-sad="2" data-rank="5" data-hasmaxattribute="True" data-year="2001"}
**Album:** *Jane Doe* (2001)\
**Genres:** Mathcore
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Sad</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #4269D0FF; width:40.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Angry</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #FF5D45FF; width:100.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dark</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #1B1B1BFF; width:60.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Passion</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #A463F2FF; width:100.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="2WGbgnDQF6A"></lite-youtube></div></details>
## 4. Mac Miller - Good News{.song data-passion="0" data-dreamy="0" data-dark="0" data-groovy="0" data-angry="0" data-happy="0" data-sad="6" data-rank="4" data-hasmaxattribute="True" data-year="2020"}
**Album:** *Circles* (2020)\
**Genres:** Neo-Soul
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"><span class="badge bg-primary rounded-pill">🏆 Most Tears Shed</span></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Sad</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #4269D0FF; width:100.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="aIHF7u9Wwiw"></lite-youtube></div></details>
## 3. Sam Cooke - A Change Is Gonna Come{.song data-passion="4" data-dreamy="0" data-dark="0" data-groovy="0" data-angry="0" data-happy="1" data-sad="4" data-rank="3" data-hasmaxattribute="False" data-year="1964"}
**Album:** *Ain’t That Good News* (1964)\
**Genres:** Soul
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"><span class="badge bg-primary rounded-pill">🏆 Most Hopeful Song</span></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Sad</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #4269D0FF; width:80.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Happy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #6CC5B0FF; width:20.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Passion</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #A463F2FF; width:80.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="1oZ6Z9xRxo8"></lite-youtube></div></details>
## 2. Carissa's Wierd - September Come Take This Heart Away{.song data-passion="0" data-dreamy="2" data-dark="0" data-groovy="0" data-angry="0" data-happy="0" data-sad="7" data-rank="2" data-hasmaxattribute="True" data-year="2002"}
**Album:** *Songs About Leaving* (2002)\
**Genres:** Slowcore
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"><span class="badge bg-primary rounded-pill">🏆 Heaviest Heart</span></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Sad</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #4269D0FF; width:100.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dreamy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #F0BD3CFF; width:40.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="cYtdQccn54I"></lite-youtube></div></details>
## 1. Light Bringer - Hyperion{.song data-passion="5" data-dreamy="0" data-dark="0" data-groovy="0" data-angry="0" data-happy="7" data-sad="0" data-rank="1" data-hasmaxattribute="True" data-year="2013"}
**Album:** *Scenes of Infinity* (2013)\
**Genres:** Power Metal
<div class="toggle-tags"><div class="d-flex gap-2 mb-2 mt-2"><span class="badge bg-primary rounded-pill">🏆 Most Inspirational Song</span></div></div>
<div class='toggle-mood'><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Happy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #6CC5B0FF; width:100.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Passion</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #A463F2FF; width:100.0%;" role="progressbar"></div></div></div><br></div><details><summary>Listen here</summary><div class="lite-youtube-style"><lite-youtube videoid="Qnqud-E4aXM"></lite-youtube></div></details>
</div>## Overall Mood Distribution
<div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Sad</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #4269D0FF; width:100.0%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Angry</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #FF5D45FF; width:48.10810810810811%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Happy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #6CC5B0FF; width:59.45945945945946%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dark</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #1B1B1BFF; width:35.67567567567568%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Groovy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #9C6B4EFF; width:23.783783783783786%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Dreamy</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #F0BD3CFF; width:70.8108108108108%;" role="progressbar"></div></div></div><div style="display:grid; grid-template-columns: 70px 160px; align-items:center; margin-bottom:0px;"><div>Passion</div><div class="progress" style="height:14px;"><div class="progress-bar" style="background-color: #A463F2FF; width:91.8918918918919%;" role="progressbar"></div></div></div>

## Stats

```{python}
import numpy as np
import pandas as pd
import plotly.express as px
import plotly.io as pio

pio.templates["my_default"] = pio.templates["simple_white"]
pio.templates["my_default"].layout.update(
    font=dict(size=15),
    xaxis=dict(tickfont=dict(size=16)),
    yaxis=dict(tickfont=dict(size=16)),
    margin=dict(l=60, r=30, t=50, b=60),
    width=700,
    height=500
)
pio.templates["my_default"].layout.colorway = ["#4269D0"]

INPUT_CSV = "../data/songs.csv"
df = pd.read_csv(INPUT_CSV)
df = df.head(100)
df = df.sort_index(ascending=False)
df["Decade"] = df["Year"].astype(str).str.slice(0,-3) + ["0"]

counts = (
    df.groupby(["Country", "CountryName"])
      .size()
      .reset_index(name="count")
).sort_values("count", ascending=False).rename(columns={"count": "Count"})

# Country bars

fig = px.bar(
    counts,
    x="Country",
    y="Count",
    hover_data=["CountryName"],
    text="Count",
    template="my_default"
)

fig.update_traces(textposition="outside")

fig.update_layout(
    template="simple_white",
    yaxis_title=None
)

fig.update_xaxes(
    showline=True,
    linecolor="black",
    ticks="outside",
    mirror=False,
    fixedrange=True
)

fig.update_yaxes(
    showline=True,
    linecolor="black",
    ticks="outside",
    mirror=False,
    fixedrange=True,
    title="Count"
)
fig.show()

# Decade histogram

dd = df[df["Decade"] != "0"].sort_values(by="Decade")
dd_counts = dd["Decade"].value_counts().sort_index()

fig = px.bar(
    x=dd_counts.index,
    y=dd_counts.values,
    template="my_default",
    text=dd_counts.values
)

fig.update_traces(textposition="outside")
fig.update_layout(
    yaxis_title=None
)
fig.update_xaxes(
    showline=True,
    linecolor="black",
    ticks="outside",
    mirror=False,
    fixedrange=True,
    title="Decade"
)

fig.update_yaxes(
    showline=True,
    linecolor="black",
    ticks="outside",
    mirror=False,
    fixedrange=True,
    title="Count"
)
fig.show()
```

```{python}
## Views vs duration scatterplot
def number_formatter(n):
    for unit in ["", "k", "M", "B"]:
        if abs(n) < 1000:
            return f"{n:.0f}{unit}".rstrip("0").rstrip(".")
        n /= 1000

s = df["Duration"].astype(str)
s = s.str.replace(".00", "")
s = s.where(s.str.count(":") != 1, "00:" + s)
df["Duration"] = pd.to_timedelta(s,  errors="coerce")
df["ViewsFormatted"] = df["Views"].apply(number_formatter)
df["DurationFormatted"] = df["Duration"].astype(str).str.replace("0 days 00:", "")
df["DurationSeconds"] = df["Duration"].dt.total_seconds()

fig = px.scatter(
    df,
    x="DurationSeconds",
    y=np.log10(df["Views"]),
    custom_data=["Title", "ViewsFormatted", "DurationFormatted"],
    template="my_default"
)

fig.update_traces(
    marker_size=10,
    hovertemplate=(
        "<b>%{customdata[0]}</b><br>"
        "Views: %{customdata[1]}<br>"
        "Duration: %{customdata[2]}"
        "<extra></extra>"
    ),
)

fig.update_xaxes(
    showline=True,
    linecolor="black",
    ticks="outside",
    mirror=False,
    fixedrange=True,
    title="Duration (s)"
)

fig.update_yaxes(
    showline=True,
    linecolor="black",
    ticks="outside",
    mirror=False,
    title="log10(Views)",
    fixedrange=True,
)

fig.update_layout(
    dragmode=False,
    modebar_remove=["zoom", "pan", "select", "lasso"]
)

fig.show()
```

```{ojs}

function wrapSections() {
  const h2s = Array.from(document.querySelectorAll("h2.song"))

  h2s.forEach(h2 => {
    const wrapper = document.createElement("div")
    wrapper.className = "section"

    h2.parentNode.insertBefore(wrapper, h2)

    let node = h2
    while (node) {
      const next = node.nextSibling
      wrapper.appendChild(node)

      if (!next || (next.nodeType === 1 && next.tagName === "H2")) {
        break
      }

      node = next
    }
  })
}
wrapSections()
```
<script>

function filterSections(hasmaxattribute) {
  document.querySelectorAll(".section").forEach(section => {
    const h2 = section.querySelector("h2")
    const match = hasmaxattribute === "all" || 
                  h2.dataset.hasmaxattribute === hasmaxattribute

    section.style.display = match ? "" : "none"
  })
}

function sortSections(by = "rank", direction = "desc", numeric = true) {
  const container = document.querySelector(".songs") // adjust if needed
  const sections = Array.from(document.querySelectorAll(".section"))
    console.log(by)
  if (numeric) {
    sections.sort((a, b) => {
    const aVal = Number(a.querySelector("h2").dataset[by])
    const bVal = Number(b.querySelector("h2").dataset[by])
    return direction === "desc" ? bVal - aVal : aVal - bVal
    })
  } else {
    sections.sort((a, b) => {
        const aVal = a.querySelector("h2").dataset[by]
        const bVal = b.querySelector("h2").dataset[by]

        return direction === "desc"
        ? bVal.localeCompare(aVal)
        : aVal.localeCompare(bVal)
    })
  }

  sections.forEach(section => container.appendChild(section))
}

const switchMaxMood = document.getElementById("toggleMaxMood");
  switchMaxMood.addEventListener("change", (e) => {
    if (e.target.checked) {
      filterSections("True");
    } else {
      filterSections("all");
    }
  });
</script>
