---
title: "Top 100 Songs"
format: html
toc: false
echo: false
---


The greatest songs of all time!!! (According to me)\


::: {.callout-note title="Note"}
- One song per artist.
- Classical music is not eligible and will be covered in a separate list.
:::


<div class="dropdown">
  <button class="btn btn-primary dropdown-toggle" type="button"
          data-bs-toggle="dropdown" aria-expanded="false">
    Sort
  </button>
  <ul class="dropdown-menu">
    <li>
      <a class="dropdown-item" href="#"
         onclick="sortSections('rank','desc'); return false;">
        Rank
      </a>
    </li>
    <li>
      <a class="dropdown-item" href="#"
         onclick="sortSections('year','desc'); return false;">
        Year
      </a>
    </li>
    <li>
      <a class="dropdown-item" href="#"
         onclick="sortSections('sad','desc'); return false;">
        Sad
      </a>
    </li>
    <li>
      <a class="dropdown-item" href="#"
         onclick="sortSections('angry','desc'); return false;">
        Angry
      </a>
    </li>
    <li>
      <a class="dropdown-item" href="#"
         onclick="sortSections('happy','desc'); return false;">
        Happy
      </a>
    </li>
    <li>
      <a class="dropdown-item" href="#"
         onclick="sortSections('dark','desc'); return false;">
        Dark
      </a>
    </li>
    <li>
      <a class="dropdown-item" href="#"
         onclick="sortSections('groovy','desc'); return false;">
        Groovy
      </a>
    </li>
    <li>
      <a class="dropdown-item" href="#"
         onclick="sortSections('dreamy','desc'); return false;">
        Dreamy
      </a>
    </li>
    <li>
      <a class="dropdown-item" href="#"
         onclick="sortSections('passion','desc'); return false;">
        Passion
      </a>
    </li>
  </ul>
</div>

<!---
<div class="d-flex gap-4 mb-3">
<div class="form-check form-switch">
<input class="form-check-input" type="checkbox" id="toggleMaxMood">
<label class="form-check-label" for="toggleMaxMood">Max. Mood</label>
</div>

<div class="form-check form-switch mt-4">
<input class="form-check-input" type="checkbox" id="toggleMood" checked>
<label class="form-check-label" for="toggleMood">Mood Levels</label>
</div>

<div class="form-check form-switch mt-4">
<input class="form-check-input" type="checkbox" id="toggleTags" checked>
<label class="form-check-label" for="toggleTags">Tags</label>
</div></div>
--->


{{CONTENT}}

## Stats

```{python}
import numpy as np
import pandas as pd
import plotly.express as px
INPUT_CSV = "../data/songs.csv"
df = pd.read_csv(INPUT_CSV)
df = df.sort_index(ascending=False)

counts = (
    df.groupby(["Country", "CountryName"])
      .size()
      .reset_index(name="count")
).sort_values("count", ascending=False).rename(columns={"count": "Count"})

fig = px.bar(
    counts,
    x="Country",
    y="Count",
    hover_data=["CountryName"]
)

fig.update_layout(yaxis_title=None)
fig.show()

# Decade histogram
df["Decade"] = df["Year"].astype(str).str.slice(0,-3) + ["0"]
fig = px.histogram(df[df["Decade"]!="0"].sort_values(by="Decade"), x="Decade")
fig.update_layout(yaxis_title=None)
fig.show()

# Views histogram
fig = px.histogram(np.log10(df["Views"]))
fig.update_layout(yaxis_title=None,xaxis_title="log10(YouTube Views)",showlegend=False)
fig.show()
```

```{ojs}

function wrapSections() {
  const h2s = Array.from(document.querySelectorAll("h2.song"))

  h2s.forEach(h2 => {
    const wrapper = document.createElement("div")
    wrapper.className = "section"

    h2.parentNode.insertBefore(wrapper, h2)

    let node = h2
    while (node) {
      const next = node.nextSibling
      wrapper.appendChild(node)

      if (!next || (next.nodeType === 1 && next.tagName === "H2")) {
        break
      }

      node = next
    }
  })
}
wrapSections()
```
<script>

function filterSections(hasmaxattribute) {
  document.querySelectorAll(".section").forEach(section => {
    const h2 = section.querySelector("h2")
    const match = hasmaxattribute === "all" || 
                  h2.dataset.hasmaxattribute === hasmaxattribute

    section.style.display = match ? "" : "none"
  })
}

function sortSections(by = "rank", direction = "desc", numeric = true) {
  const container = document.querySelector(".songs") // adjust if needed
  const sections = Array.from(document.querySelectorAll(".section"))
    console.log(by)
  if (numeric) {
    sections.sort((a, b) => {
    const aVal = Number(a.querySelector("h2").dataset[by])
    const bVal = Number(b.querySelector("h2").dataset[by])
    return direction === "desc" ? bVal - aVal : aVal - bVal
    })
  } else {
    sections.sort((a, b) => {
        const aVal = a.querySelector("h2").dataset[by]
        const bVal = b.querySelector("h2").dataset[by]

        return direction === "desc"
        ? bVal.localeCompare(aVal)
        : aVal.localeCompare(bVal)
    })
  }

  sections.forEach(section => container.appendChild(section))
}

const switchMaxMood = document.getElementById("toggleMaxMood");
  switchMaxMood.addEventListener("change", (e) => {
    if (e.target.checked) {
      filterSections("True");
    } else {
      filterSections("all");
    }
  });
</script>
