---
title: "Top 100 Albums"
format: html
toc: false
echo: false
---


The greatest ablums of all time!!! (According to me)\


::: {.callout-note title="Note"}
- Work in progress...
- One album per artist.
- Classical releases are not eligible and will be covered in a separate list.
:::


<div class="dropdown">
  <button class="btn btn-primary dropdown-toggle" type="button"
          data-bs-toggle="dropdown" aria-expanded="false">
    Sort
  </button>
  <ul class="dropdown-menu">
    <li>
      <a class="dropdown-item" href="#"
         onclick="sortSections('rank','desc'); return false;">
        Rank
      </a>
    </li>
    <li>
      <a class="dropdown-item" href="#"
         onclick="sortSections('year','desc'); return false;">
        Year
      </a>
    </li>
    <li>
      <a class="dropdown-item" href="#"
         onclick="sortSections('sad','desc'); return false;">
        Sad
      </a>
    </li>
    <li>
      <a class="dropdown-item" href="#"
         onclick="sortSections('angry','desc'); return false;">
        Angry
      </a>
    </li>
    <li>
      <a class="dropdown-item" href="#"
         onclick="sortSections('happy','desc'); return false;">
        Happy
      </a>
    </li>
    <li>
      <a class="dropdown-item" href="#"
         onclick="sortSections('dark','desc'); return false;">
        Dark
      </a>
    </li>
    <li>
      <a class="dropdown-item" href="#"
         onclick="sortSections('groovy','desc'); return false;">
        Groovy
      </a>
    </li>
    <li>
      <a class="dropdown-item" href="#"
         onclick="sortSections('dreamy','desc'); return false;">
        Dreamy
      </a>
    </li>
    <li>
      <a class="dropdown-item" href="#"
         onclick="sortSections('passion','desc'); return false;">
        Passion
      </a>
    </li>
  </ul>
</div>


{{CONTENT}}

## Stats

```{python}
import numpy as np
import pandas as pd
import plotly.express as px
import plotly.io as pio

pio.templates["my_default"] = pio.templates["simple_white"]
pio.templates["my_default"].layout.update(
    font=dict(size=15),
    xaxis=dict(tickfont=dict(size=16)),
    yaxis=dict(tickfont=dict(size=16)),
    margin=dict(l=60, r=30, t=50, b=60),
    width=700,
    height=500
)
pio.templates["my_default"].layout.colorway = ["#4269D0"]

INPUT_CSV = "../data/albums.csv"
df = pd.read_csv(INPUT_CSV)
df = df.head(100)
df = df.sort_index(ascending=False)
df["Decade"] = df["Year"].astype(str).str.slice(0,-3) + ["0"]

counts = (
    df.groupby(["Country", "CountryName"])
      .size()
      .reset_index(name="count")
).sort_values("count", ascending=False).rename(columns={"count": "Count"})

# Country bars

fig = px.bar(
    counts,
    x="Country",
    y="Count",
    hover_data=["CountryName"],
    text="Count",
    template="my_default"
)

fig.update_traces(textposition="outside")

fig.update_layout(
    template="simple_white",
    yaxis_title=None
)

fig.update_xaxes(
    showline=True,
    linecolor="black",
    ticks="outside",
    mirror=False,
    fixedrange=True
)

fig.update_yaxes(
    showline=True,
    linecolor="black",
    ticks="outside",
    mirror=False,
    fixedrange=True,
    title="Count"
)
fig.show()

# Decade histogram

dd = df[df["Decade"] != "0"].sort_values(by="Decade")
dd_counts = dd["Decade"].value_counts().sort_index()

fig = px.bar(
    x=dd_counts.index,
    y=dd_counts.values,
    template="my_default",
    text=dd_counts.values
)

fig.update_traces(textposition="outside")
fig.update_layout(
    yaxis_title=None
)
fig.update_xaxes(
    showline=True,
    linecolor="black",
    ticks="outside",
    mirror=False,
    fixedrange=True,
    title="Decade"
)

fig.update_yaxes(
    showline=True,
    linecolor="black",
    ticks="outside",
    mirror=False,
    fixedrange=True,
    title="Count"
)
fig.show()
```

```{ojs}

function wrapSections() {
  const h2s = Array.from(document.querySelectorAll("h2.album"))

  h2s.forEach(h2 => {
    const wrapper = document.createElement("div")
    wrapper.className = "section"

    h2.parentNode.insertBefore(wrapper, h2)

    let node = h2
    while (node) {
      const next = node.nextSibling
      wrapper.appendChild(node)

      if (!next || (next.nodeType === 1 && next.tagName === "H2")) {
        break
      }

      node = next
    }
  })
}
wrapSections()
```
<script>

function filterSections(hasmaxattribute) {
  document.querySelectorAll(".section").forEach(section => {
    const h2 = section.querySelector("h2")
    const match = hasmaxattribute === "all" || 
                  h2.dataset.hasmaxattribute === hasmaxattribute

    section.style.display = match ? "" : "none"
  })
}

function sortSections(by = "rank", direction = "desc", numeric = true) {
  const container = document.querySelector(".album") // adjust if needed
  const sections = Array.from(document.querySelectorAll(".section"))
    console.log(by)
  if (numeric) {
    sections.sort((a, b) => {
    const aVal = Number(a.querySelector("h2").dataset[by])
    const bVal = Number(b.querySelector("h2").dataset[by])
    return direction === "desc" ? bVal - aVal : aVal - bVal
    })
  } else {
    sections.sort((a, b) => {
        const aVal = a.querySelector("h2").dataset[by]
        const bVal = b.querySelector("h2").dataset[by]

        return direction === "desc"
        ? bVal.localeCompare(aVal)
        : aVal.localeCompare(bVal)
    })
  }

  sections.forEach(section => container.appendChild(section))
}

const switchMaxMood = document.getElementById("toggleMaxMood");
  switchMaxMood.addEventListener("change", (e) => {
    if (e.target.checked) {
      filterSections("True");
    } else {
      filterSections("all");
    }
  });
</script>
